#!/bin/bash

. scripts/memoryMonitor
memoryMonitor $$ >log.memoryMonitor &
memMonPid=$!

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh
rm -r constant/polyMesh
cp -r 3/polyMesh constant/polyMesh
runApplication createPatch
rm -r constant/polyMesh
cp -r 4/polyMesh constant/polyMesh
rm -r 1 2 3 4
runApplication decomposePar -force
runParallel buoyantSimpleFoam
runApplication gnuplot Residuals
runApplication reconstructPar -latestTime
runApplication postProcess -func cuttingPlane


